/// CAR

### Add Car
POST http://localhost:8080/api/cars/save
Content-Type: application/json

{
  "model": "Aventador",
  "year": 2021,
  "horsepower": 730,
  "price": 300000
}

### Delete Car
DELETE http://localhost:8080/api/cars/delete
Content-Type: application/json

{
  "model": "Aventador",
  "year": 2021,
  "horsepower": 730,
  "price": 300000
}


### Get All Cars
GET http://localhost:8080/api/cars




/// ADMIN


### Add Admin
POST http://localhost:8080/api/admins/save
Content-Type: application/json

{
  "email": "bibipulpix@gmail.com",
  "password": "parola"
}


### Get All Admins
GET http://localhost:8080/api/admins





/// CLIENT
### Get All Client
GET http://localhost:8080/api/clients





